# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dotiw}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bigg"]
  s.date = %q{2010-10-02}
  s.description = %q{Better distance_of_time_in_words for Rails}
  s.email = %q{radarlistener@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files        = `git ls-files`.split("\n")
  s.executables  = `git ls-files`.split("\n").map{|f| f =~ /^bin\/(.*)/ ? $1 : nil}.compact
  s.homepage = %q{http://github.com/radar/dotiw}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Better distance_of_time_in_words for Rails}
  
  s.add_development_dependency "bundler", ">= 1.0.0"
  s.add_development_dependency "rspec", "~> 2.3"
  s.add_dependency "activerecord", ">= 3.0.0"
  s.add_dependency "actionpack",">= 3.0.0"
  s.add_dependency "chronic"
end

